apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  ingresses:
    - {{ingress}}
  liveness:
    path: /internal/health
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 2000m
      memory: 1000Mi
    requests:
      cpu: 1000m
      memory: 600Mi
  kafka:
    pool: {{kafkaPool}}
